plugins {
    id 'java'
    id 'application'
}

group = 'by.lizaveta'
version = '1.0'

application {
    mainClass = 'by.lizaveta.shift.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'by.lizaveta.shift.Main'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}